server:
  port: 8080

spring:
  datasource:
    name: test
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.149:3306/test
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:com/example/demo_jsqlparser/mapper/xml/IUserMapper.xml